INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2111,    'JCP Inc.',            103,     50000);
INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2102,    'First Corp.',         101,     65000);
INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2103,    'Acme Mfg.',           105,     50000);
INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2123,    'Carter & Sons',       102,     40000);
INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2107,    'Ace lnternational',   110,     35000);
INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2115,    'Smithson Corp.',      101,     20000);
INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2101,    'Jones Mfg.',          106,     65000);
INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2112,    'Zetacorp',            108,     50000);
INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2121,    'QMA Assoc.',          103,     45000);
INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2114,    '0rion Corp.',         102,     20000);
INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2124,    'Peter Brothers',      107,     40000);
INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2108,    'Holm & Landis',       109,     55000);
INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2117,    'J.P. Sinclair',       106,     35000);
INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2122,    'Three-Way Lines',     105,     30000);
INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2120,    'Rico Enterprises',    102,     50000);
INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2106,    'Fred Lewis Corp.',    102,     65000);
INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2119,    'Solomon Inc.',        109,     25000);
INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2118,    'Midwest Systems',     108,     60000);
INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2113,    'Ian & Schmidt',       104,     20000);
INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2109,    'Chen Associates',     103,     25000);
INSERT INTO customers (cust_num, company, cust_rep, credit_limit) VALUES (2105,    'AAA Investments',     101,     45000);
