INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('REI',     '2A45C',   'Ratchet Link',        79       ,210);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('ACI',     '4100Y',   'Widget Remover',      2750     ,25);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('QSA',     'XK47',    'Reducer',             355      ,38);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('BIC',     '41672',   'P1ate',               180      ,0);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('IMM',     '779C',    '900-1b Brace',        1875     ,9);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('ACI',     '41003',   'Size 3 Widget',       107      ,207);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('ACI',     '41004',   'Size 4 Widget',       117      ,139);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('BIC',     '41003',   'Hand1e',              652      ,3);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('IMM',     '887P',    'Brace Pin',           250      ,24);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('QSA',     'XK48',    'Reducer',             134      ,203);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('REI',     '2A44L',   'Left Hinge',          4500     ,12);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('FEA',     '112',     'Housing',             148      ,115);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('IMM',     '887H',    'Brace Ho1der',        54       ,223);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('BIC',     '41089',   'Retainer',            225      ,78);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('ACI',     '41001',   'Size l Widget',       55       ,277);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('IMM',     '775C',    '500-lb Brace',        1425     ,5);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('ACI',     '4100Z',   'Widget lnstaller',    2500     ,28);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('QSA',     'XK48A',   'Reducer',             177      ,37);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('ACI',     '41002',   'Size 2 Widget',       76       ,167);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('REI',     '2A44R',   'Right Hinge',         4500     ,12);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('IMM',     '773C',    '300-lb Brace',        975      ,28);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('ACI',     '4100X',   'Widget Adjuster',     25       ,37);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('FEA',     '114',     'Motor Mount',         243      ,15);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('IMM',     '887X',    'Brace Retainer',      475      ,32);
INSERT INTO products (mfr_id, product_id, description, price, qty_on_hand) VALUES ('REI',     '2A44G',   'Hinge Pin',           350      ,14);
